# Generated by Django 4.0.3 on 2022-03-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datasheet',
            old_name='descriptoin',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='profession',
            old_name='descriptoin',
            new_name='description',
        ),
    ]
