# Generated by Django 4.0.3 on 2022-03-22 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_descriptoin_datasheet_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
