# Generated by Django 4.0.3 on 2022-03-23 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_customer_doc_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='doc_num',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
